name: Release to Production

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref or sha to deploy'
        required: true
        default: 'main'

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://production.example.com

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Deploy to Production
      run: |
        echo "Deploying to Production Environment..."
        # Your production deployment commands go here
        echo "Production deployment completed."
